name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: PHP - build images
      run: make php version=${{ matrix.php }} os=${{ matrix.os }} composer=${{ matrix.composer }} packages=${{ matrix.packages }}
    strategy:
      matrix:
        os: [alpine3.12]
        php: [7.3.19, 7.4.7, 8.0-rc]
        composer: [1.10.8]
        packages: [mysql, postgres]
