name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.4.15, 8.0.2]
        os: [alpine]
        osVersion: [3.13]
        depManagerVersion: [2.0.9]
        installs: [mysql, postgres]

    steps:
    - uses: actions/checkout@v2

    - name: PHP - Build
      run: |
        make build \
          lang=php \
          version=${{ matrix.php }} \
          os=${{ matrix.os }} \
          osVersion=${{ matrix.osVersion }} \
          depManagerVersion=${{ matrix.depManagerVersion }} \
          installs=${{ matrix.installs }}

    - name: PHP - Publish
      if: github.ref == 'refs/heads/main'
      run: |
        make login registry=ghcr.io username=fefas password=${{ secrets.GHRC_TOKEN }}
        make publish \
          registry=ghcr.io \
          lang=php \
          version=${{ matrix.php }} \
          os=${{ matrix.os }} \
          osVersion=${{ matrix.osVersion }} \
          depManagerVersion=${{ matrix.depManagerVersion }} \
          installs=${{ matrix.installs }}
